const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");

const rootDir = path.resolve(__dirname, "..");
const reportPath = path.join(rootDir, "output", "production-expansion", "phase4-9618-final-coverage-reaudit-stability-report.json");
const report = JSON.parse(fs.readFileSync(reportPath, "utf8"));

assert.equal(report.generatedFor, "Phase-4-9618-Final-Coverage-Re-Audit-and-Stability-Validation-Plan");
assert.equal(report.status, "PASS");
assert.equal(report.phaseId, "Phase 4");
assert.equal(report.auditOnly, true);
assert.equal(report.productionWrite, false);
assert.equal(report.generateStaging, false);
assert.equal(report.sourceAudit.status, "PASS");
assert.equal(report.sourceAudit.sourcePairs, 118);
assert.equal(report.sourceAudit.completeSourcePairs, 118);
assert.equal(report.sourceAudit.incompleteSourcePairs, 0);
assert.equal(report.sourceAudit.duplicateSourceCount, 0);
assert.equal(report.stagingAudit.status, "PASS");
assert.equal(report.stagingAudit.pairingKeysVerified, 118);
assert.deepEqual(report.stagingAudit.missingStagingPairingKeys, []);
assert.deepEqual(report.stagingAudit.partialStagingPairingKeys, []);
assert.equal(report.publicationAudit.status, "PASS");
assert.equal(report.publicationAudit.publishedPairs, 105);
assert.equal(report.publicationAudit.blockedPairs, 13);
assert.equal(report.publicationAudit.classifiedTotal, 118);
assert.equal(report.phase3Reconciliation.status, "PASS");
assert.equal(report.phase3Reconciliation.publishedPairsAdded, 79);
assert.equal(report.phase3Reconciliation.stagingPairsAdded, 92);
assert.equal(report.phase3Reconciliation.stagingArtifactsAdded, 184);
assert.equal(report.batchAudit.status, "PASS");
assert.equal(report.batchAudit.batchCount, 9);
assert.equal(report.batchDeltaAudit.status, "PASS");
assert.equal(report.batchDeltaAudit.batchesAudited, 9);
assert.deepEqual(report.batchDeltaAudit.batchesMissingDeltaEvidence, []);
assert.deepEqual(report.batchDeltaAudit.batchesWithDeltaMismatch, []);
assert(report.batchDeltaAudit.results.every((batch) => batch.deltasMatch));
assert.equal(report.blockedPairAudit.status, "PASS");
assert.equal(report.blockedPairAudit.pairs.length, 13);
assert.deepEqual(report.blockedPairAudit.blockedPairsPublishedByMistake, []);
assert(report.blockedPairAudit.pairs.every((pair) => pair.classification === "BLOCKED" && !pair.productionPublished && pair.blockerEvidenceAvailable));
assert.equal(report.strictEligiblePublicationAudit.status, "PASS");
assert.equal(report.strictEligiblePublicationAudit.strictEligibleCount, 79);
assert.equal(report.strictEligiblePublicationAudit.strictEligiblePublishedCount, 79);
assert.deepEqual(report.strictEligiblePublicationAudit.strictEligibleUnpublished, []);
assert.equal(report.pairVerificationAudit.status, "PASS");
assert.equal(report.pairVerificationAudit.verifiedPairCount, 105);
assert.deepEqual(report.pairVerificationAudit.failures, []);
assert.equal(report.frontendVerification.status, "PASS");
assert(Object.values(report.frontendVerification.checks).every((status) => status === "PASS"));
for (const key of ["productionIntegrity", "stagingIntegrity", "sourceAssetIntegrity", "parserIntegrity", "canonicalIntegrity"]) assert.equal(report[key].unchanged, true);
assert.equal(report.productionIntegrity.existingRecordsUnchanged, true);
assert.deepEqual(report.stagingIntegrity.added, []);
assert.deepEqual(report.stagingIntegrity.modified, []);
assert.deepEqual(report.stagingIntegrity.deleted, []);
assert(Object.values(report.stableModules).every((modified) => modified === false));
assert(Object.values(report.closureChecks).every(Boolean));
assert.equal(report.closureDecision, "PASS_WITH_KNOWN_BLOCKERS");
assert.equal(report.remainingIssues.length, 13);
assert.equal(report.next.decision, "Dedicated Blocked-Pair Investigation Phase");
assert.deepEqual(report.regression.architectureFailures, []);
assert.deepEqual(report.regression.documentRoleRegressions, []);
