const assert = require("node:assert/strict");
const fs = require("node:fs");
const path = require("node:path");
const { readProductionStore } = require("../src/ingestion");

const rootDir = path.resolve(__dirname, "..");
const reportPath = path.join(rootDir, "output", "production-expansion", "phase2-9618-duplicate-source-cleanup-report.json");
const report = JSON.parse(fs.readFileSync(reportPath, "utf8"));
const store = readProductionStore(path.join(rootDir, "output", "production", "production-store.json"));

assert.equal(report.generatedFor, "Phase-2-9618-Duplicate-Source-Investigation-and-Cleanup-Plan");
assert.equal(report.status, "PASS");
assert.equal(report.phaseId, "Phase 2");
assert.equal(report.targetPair.pairingKey, "9618-2021-ON-41");
assert.equal(report.duplicateCandidates.length, 2);
assert.equal(report.fileComparison.byteIdentical, true);
assert.equal(report.fileComparison.fileSizeMatches, true);
assert.equal(report.fileComparison.pageCountMatches, true);
assert.equal(report.fileComparison.metadataMatches, true);
assert.equal(report.fileComparison.firstPageTextMatches, true);
assert.equal(report.hashComparison.sameFile, true);
assert.equal(report.hashComparison.candidateASha256, report.hashComparison.candidateBSha256);
assert.equal(report.hashComparison.candidateASha256, "f95f8e857df8a51e9fffe6f9011ac74ce446eb243084580db30b8deff0ea37ec");
assert.equal(report.identityVerification.candidateA.status, "PASS");
assert.equal(report.identityVerification.candidateB.status, "PASS");
assert.equal(report.canonicalDecision.status, "PASS");
assert.match(report.canonicalDecision.retainedPath, /2021 Oct Nov\/9618_w21_ms_41\.pdf$/);
assert.match(report.canonicalDecision.removedPath, /2022 May June\/9618_w21_ms_41\.pdf$/);
assert.equal(report.cleanupAction.performed, true);
assert.equal(report.cleanupAction.action, "REMOVE_CONFIRMED_DUPLICATE_COPY");
assert.equal(report.sourceChanges.onlyIntendedDuplicateSourceChanged, true);
assert.equal(report.sourceChanges.canonicalSourceRetained, true);
assert.equal(report.sourceChanges.duplicateSourceRemoved, true);
assert.equal(report.sourceAssetIntegrity.unchangedExceptIntendedDuplicate, true);
assert.deepEqual(report.sourceAssetIntegrity.unexpectedPdfAssetChanges, []);
assert.equal(report.inventoryBefore.duplicateSourceCount, 1);
assert.equal(report.inventoryAfter.duplicateSourceCount, 0);
assert.equal(report.inventoryBefore.sourcePairs, 118);
assert.equal(report.inventoryAfter.sourcePairs, 118);
assert.equal(report.inventoryAfter.completeSourcePairs, 118);
assert.equal(report.inventoryAfter.incompleteSourcePairs, 0);
assert.equal(report.inventoryBefore.totalPdfFiles - report.inventoryAfter.totalPdfFiles, 1);
assert.equal(report.inventoryAfter.totalPdfFiles, 266);
assert.equal(report.productionIntegrity.unchanged, true);
assert.equal(report.stagingIntegrity.unchanged, true);
assert.equal(report.parserIntegrity.unchanged, true);
assert.equal(report.canonicalIntegrity.unchanged, true);
assert.deepEqual(report.regression.architectureFailures, []);
assert.deepEqual(report.regression.documentRoleRegressions, []);
assert.equal(report.next.phaseId, "Phase 3");

assert(fs.existsSync(report.canonicalDecision.retainedPath));
assert(!fs.existsSync(report.canonicalDecision.removedPath));
assert(store.papers.some((paper) => paper.id === "9618-2021-ON-41-MS"));
assert(store.pairings.some((pairing) => pairing.pairingKey === "9618-2021-ON-41"));
