"use strict";

const ALLOWED_STATUSES = new Set([
  "DRAFT",
  "VALIDATED",
  "READY_FOR_HUMAN_REVIEW",
  "APPROVED",
  "CURRENT",
  "SUPERSEDED",
  "HISTORICAL",
  "ARCHIVED",
  "IMMUTABLE_EVIDENCE",
  "BLOCKED",
]);

const RULES = Object.freeze({
  NAME_LONG_LIVED: "DOC-NAME-001",
  NAME_MAINTENANCE_MD: "DOC-NAME-002",
  NAME_PAIRED_JSON: "DOC-NAME-003",
  NAME_AMBIGUOUS: "DOC-NAME-004",
  META_STATUS: "DOC-META-001",
  META_OWNER: "DOC-META-002",
  META_CREATED_AT: "DOC-META-003",
  META_AUTHORITY: "DOC-META-004",
  META_RELATED: "DOC-META-005",
  LIFECYCLE_INVALID: "DOC-LIFECYCLE-001",
  LIFECYCLE_PASS_STATUS: "DOC-LIFECYCLE-002",
  LIFECYCLE_AUTHORITY_SYNC: "DOC-LIFECYCLE-003",
  LIFECYCLE_SUPERSEDED: "DOC-LIFECYCLE-004",
  LIFECYCLE_APPROVAL: "DOC-LIFECYCLE-005",
  LINK_MISSING: "DOC-LINK-001",
  LINK_ANCHOR: "DOC-LINK-002",
  LINK_ABSOLUTE: "DOC-LINK-003",
  LINK_ARCHIVE_CURRENT: "DOC-LINK-004",
  LINK_DELETED_TARGET: "DOC-LINK-005",
  AUTH_DUPLICATE: "DOC-AUTH-001",
  AUTH_TARGET_MISSING: "DOC-AUTH-002",
  AUTH_ARCHIVE: "DOC-AUTH-003",
  AUTH_TARGET_STATE: "DOC-AUTH-004",
  AUTH_SYNC: "DOC-AUTH-005",
  EVIDENCE_PAIR_MISSING: "DOC-EVIDENCE-001",
  EVIDENCE_PAIR_MISMATCH: "DOC-EVIDENCE-002",
  EVIDENCE_SIZE: "DOC-EVIDENCE-003",
  EVIDENCE_HASH: "DOC-EVIDENCE-004",
  EVIDENCE_SELF_HASH: "DOC-EVIDENCE-005",
  EVIDENCE_JSON_PARSE: "DOC-EVIDENCE-006",
  EVIDENCE_FALSE_PASS: "DOC-EVIDENCE-007",
  EVIDENCE_ENTRY_MALFORMED: "DOC-EVIDENCE-008",
  PROTECTED_PATH: "DOC-PROTECTED-001",
  PROTECTED_HASH: "DOC-PROTECTED-002",
  PROTECTED_ARCHIVE_CHANGE: "DOC-PROTECTED-003",
  PROTECTED_BASELINE: "DOC-PROTECTED-004",
  BASELINE_NEW: "DOC-BASELINE-001",
  BASELINE_PATH: "DOC-BASELINE-002",
  BASELINE_GLOB: "DOC-BASELINE-003",
  BASELINE_REGRESSION: "DOC-BASELINE-004",
  BASELINE_STALE: "DOC-BASELINE-005",
});

// This registry is intentionally explicit: a defined rule is not considered
// implemented until the validator registers an execution path for it.
const IMPLEMENTED_RULES = new Set(Object.values(RULES));

const BASELINE_CLASSIFICATIONS = new Set([
  "LEGACY_BASELINED",
  "PROTECTED_IMMUTABLE",
  "ARCHIVED",
]);

module.exports = {
  ALLOWED_STATUSES,
  BASELINE_CLASSIFICATIONS,
  IMPLEMENTED_RULES,
  RULES,
};
